#!/usr/bin/env bash
# Shared, relocatable runtime configuration for the packaged demo.
FINAL_DEMO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export FINAL_DEMO_ROOT

if [[ -f "$FINAL_DEMO_ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$FINAL_DEMO_ROOT/.env"
  set +a
fi

export DEMO_WEB_HOST="${DEMO_WEB_HOST:-0.0.0.0}"
export DEMO_WEB_PORT="${DEMO_WEB_PORT:-4173}"
export DEMO_QA_HOST="${DEMO_QA_HOST:-127.0.0.1}"
export DEMO_QA_PORT="${DEMO_QA_PORT:-8010}"
export DEMO_RISK_HOST="${DEMO_RISK_HOST:-127.0.0.1}"
export DEMO_RISK_PORT="${DEMO_RISK_PORT:-8012}"

export FINGLMQA_ROOT="$FINAL_DEMO_ROOT/FinGLMQA"
export FINGLMQA_PHASE10_PYTHON="$FINGLMQA_ROOT/.venv-phase10/bin/python"
export FINGLMQA_API_HOST="$DEMO_QA_HOST"
export FINGLMQA_API_PORT="$DEMO_QA_PORT"
export FINGLMQA_QUEUE_CAPACITY="${FINGLMQA_QUEUE_CAPACITY:-32}"
export FINGLMQA_QUEUE_TIMEOUT_SECONDS="${FINGLMQA_QUEUE_TIMEOUT_SECONDS:-30}"
export FINGLMQA_EXECUTION_TIMEOUT_SECONDS="${FINGLMQA_EXECUTION_TIMEOUT_SECONDS:-170}"
export FINGLMQA_WORKER_STARTUP_TIMEOUT_SECONDS="${FINGLMQA_WORKER_STARTUP_TIMEOUT_SECONDS:-300}"
export FINGLMQA_SHUTDOWN_GRACE_SECONDS="${FINGLMQA_SHUTDOWN_GRACE_SECONDS:-30}"
export FINGLMQA_MAX_REQUEST_BYTES="${FINGLMQA_MAX_REQUEST_BYTES:-65536}"
export FINGLMQA_BREAKER_WINDOW_SECONDS="${FINGLMQA_BREAKER_WINDOW_SECONDS:-300}"
export FINGLMQA_BREAKER_THRESHOLD="${FINGLMQA_BREAKER_THRESHOLD:-3}"
export FINGLMQA_EVIDENCE_DEVICE="${DEMO_EVIDENCE_DEVICE:-cpu}"
export FINGLMQA_EVIDENCE_MODEL_CACHE="$FINAL_DEMO_ROOT/models"
export FINGLMQA_SUPPLEMENTAL_FACTS_ENABLED="${FINGLMQA_SUPPLEMENTAL_FACTS_ENABLED:-0}"
export FINGLMQA_RUNTIME_DIR="$FINAL_DEMO_ROOT/runtime/finglmqa"
export FINGLMQA_TRACE_DIR="$FINGLMQA_RUNTIME_DIR/traces"
export FINGLMQA_LOG_DIR="$FINGLMQA_RUNTIME_DIR/logs"
export FINGLMQA_A2RAG_PYTHON="$FINAL_DEMO_ROOT/A2RAG/.venv/bin/python"
export FINGLMQA_A2RAG_WORKER="$FINGLMQA_ROOT/scripts/query_type3_evidence.py"

export A2RAG_EMBEDDING_CACHE_DIR="$FINAL_DEMO_ROOT/models"
export A2RAG_EMBEDDING_DEVICE="$FINGLMQA_EVIDENCE_DEVICE"
export A2RAG_DOCS_DIR="$FINAL_DEMO_ROOT/output/finglm_mineru_markdown_1000_profile/04_a2rag_docs"
export A2RAG_OUTPUT_ROOT="$FINAL_DEMO_ROOT/runtime/a2rag"
export A2RAG_SAVE_DIR="$A2RAG_OUTPUT_ROOT"
if [[ -z "${FINGLMQA_LLM_ENABLED:-}" ]]; then
  if [[ -n "${A2RAG_API_KEY:-}" && -n "${A2RAG_CHAT_BASE_URL:-}" && -n "${A2RAG_CHAT_MODEL:-}" ]]; then
    export FINGLMQA_LLM_ENABLED=1
  else
    export FINGLMQA_LLM_ENABLED=0
  fi
fi

export RISK_EXPOSURE_RUN_DIR="$FINAL_DEMO_ROOT/risk_exposure_method/output/risk_exposure_sw3_430101_25_strict"
export RISK_EXPOSURE_API_HOST="$DEMO_RISK_HOST"
export RISK_EXPOSURE_API_PORT="$DEMO_RISK_PORT"
export FINGLMQA_API_URL="http://$DEMO_QA_HOST:$DEMO_QA_PORT"
export RISK_EXPOSURE_API_URL="http://$DEMO_RISK_HOST:$DEMO_RISK_PORT"
export DEMO_WEB_URL="http://127.0.0.1:$DEMO_WEB_PORT"
export DEMO_QA_URL="http://$DEMO_QA_HOST:$DEMO_QA_PORT"
export DEMO_RISK_URL="http://$DEMO_RISK_HOST:$DEMO_RISK_PORT"
export DEMO_PID_DIR="$FINAL_DEMO_ROOT/runtime/pids"
export DEMO_LOG_DIR="$FINAL_DEMO_ROOT/runtime/logs"
export PYTHONPATH="$FINGLMQA_ROOT/src:$FINAL_DEMO_ROOT/A2RAG/src:$FINAL_DEMO_ROOT${PYTHONPATH:+:$PYTHONPATH}"
